### PR TITLE
Add container test

### PR DESCRIPTION
**Pull request by LilyFaFa**

### CODE REVIEW

**Comment by LilyFaFa** [comment]
I'm not sure if this test is designed correctly, you can just think of it as a sample.

**Comment by feiskyer** [comment]
@LilyFaFa Thanks very much. Please refer [docker fake client](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/libdocker/fake_client.go) for adding a fakeClient. Generally, it should

- implements client interface (as you already done)
- contain a few set interfaces, e.g. SetContainers, SetImages, so other tests could update the internal state of fakeClient and revisit whether the state is expected after some operations
- list of called interfaces, so that tests could check whether expected interfaces are called

**Comment by LilyFaFa** [comment]
@feiskyer Thank you for your advice，I have updated the code by referring to the item in the link，this is the new code.

**Comment by feiskyer** [comment]
@LilyFaFa Thanks. Seems the PR includes some changes already merged. Could you make a rebase toward master?

**Comment by LilyFaFa** [comment]
@feiskyer Please have a look ,is this time ok?

**Comment by feiskyer** [comment]
@LilyFaFa Thanks a lot

**Pull request merged**
