### PR TITLE
Fix: Upgrade vendored to v1.12.0

### PR DESCRIPTION
**Pull request by liyanyanli**
**1.Describe what this PR did**

Upgrade vendored Kubernetes to v1.12.0

**2.Does this pull request fix one issue?**

Derivation of #344 

**3.Describe how you did it**

Upgrade vendored Kubernetes to v1.12.0

**4.Describe how to verify it**
Env:
k8s:v1.12.0
networkPlugin: weave:2.4.1

**cri-tool:**

NONE

**Kubernetes:**

runtime-docker:

Create pod:
```
[root@frakti1-12-1 ~]# kubectl create -f frakti-docker-1.yaml 
deployment.apps/frakti-docker-1 created
[root@frakti1-12-1 ~]# kubectl create -f frakti-docker-2.yaml 
deployment.apps/frakti-docker-2 created
[root@frakti1-12-1 ~]# kubectl get pod -n frakti -owide
NAME                               READY   STATUS    RESTARTS   AGE   IP           NODE           NOMINATED NODE
frakti-docker-1-6b479dbcb5-kskmz   1/1     Running   0          73s   10.32.0.14   frakti1-12-1   <none>
frakti-docker-2-79c9db55d-sffjv    1/1     Running   0          44s   10.44.0.5    frakti1-12-2   <none>
```
Cross host network:
```
[root@frakti1-12-2 ~]# docker exec -it 454ec8c7bb53 bash
[ root@frakti-docker-2-79c9db55d-sffjv:/etc/nginx ]$ ping 10.32.0.14
PING 10.32.0.14 (10.32.0.14) 56(84) bytes of data.
64 bytes from 10.32.0.14: icmp_seq=1 ttl=64 time=163 ms
64 bytes from 10.32.0.14: icmp_seq=2 ttl=64 time=63.0 ms
64 bytes from 10.32.0.14: icmp_seq=3 ttl=64 time=63.1 ms
--- 10.32.0.14 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 63.021/96.581/163.594/47.386 ms
[ root@frakti-docker-2-79c9db55d-sffjv:/etc/nginx ]$ ping 10.44.0.5
PING 10.44.0.5 (10.44.0.5) 56(84) bytes of data.
64 bytes from 10.44.0.5: icmp_seq=1 ttl=64 time=0.054 ms
64 bytes from 10.44.0.5: icmp_seq=2 ttl=64 time=0.064 ms
64 bytes from 10.44.0.5: icmp_seq=3 ttl=64 time=0.070 ms
--- 10.44.0.5 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.054/0.062/0.070/0.011 ms
[ root@frakti-docker-2-79c9db55d-sffjv:/etc/nginx ]$ 
```
Delete deployment:
```
[root@frakti1-12-1 ~]# kubectl get deployment -n frakti
NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
frakti-docker-1   1         1         1            1           10m
frakti-docker-2   1         1         1            1           10m
[root@frakti1-12-1 ~]# kubectl delete deployment frakti-docker-1 -n frakti
deployment.extensions "frakti-docker-1" deleted
[root@frakti1-12-1 ~]# kubectl delete deployment frakti-docker-2 -n frakti
deployment.extensions "frakti-docker-2" deleted
[root@frakti1-12-1 ~]# kubectl get deployment -n frakit
No resources found.
[root@frakti1-12-1 ~]# kubectl get pod -n frakti
No resources found.
```
Example yaml:
```
[root@frakti1-12-1 ~]# cat frakti-docker-1.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: frakti
  name: frakti-docker-1
  labels:
    frakti: frakti
spec:
  selector:
    matchLabels:
      frakti: frakti
  template:
    metadata:
      annotations:
        runtime.frakti.alpha.kubernetes.io/OSContainer: "true"
      labels:
        frakti: frakti
    spec:
      nodeName: frakti1-12-1
      containers:
      - name: frakti
        image: gcr.io/google_containers/nginx
        env:
          - name: TESTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
```

### CODE REVIEW

**Comment by liyanyanli** [comment]
Hi, @resouer . I think we need to upgrade golang to 1.10.4 (travis-ci).

**Comment by resouer** [comment]
Seems so. Could please update the travis config as well? So we can test this PR with new golang version.

**Comment by liyanyanli** [comment]
Hi @resouer. Is there anything else that needs to be optimized?

**Comment by resouer** [comment]
/lgtm

Good to see CI is satisfied!

**Pull request merged**
