### PR TITLE
Update vendor

### LINKED ISSUE #125: Fix hostPid support
We should update dockershim vendor to support hostPid.

Refer https://github.com/kubernetes/kubernetes/pull/44097, which already part kubernetes v1.6.2.

### PR DESCRIPTION
**Pull request by xlgao-zju**
close #125

### CODE REVIEW

**Comment by xlgao-zju** [comment]
@feiskyer Do not know what's wrong with CI. :(

**Comment by feiskyer** [comment]
Not sure what's blocked, restarted travis to check again

**Comment by feiskyer** [comment]
CI failed because of https://github.com/containernetworking/cni/issues/442

**Comment by feiskyer** [comment]
#128 is in. Restart travis.

**Pull request merged**
