### PR TITLE
Enhance test

### PR DESCRIPTION
**Pull request by Crazykev**
1. Increase frakti log level in e2e test for debug purpose, since recently we have some random stuck issue in travis.
2. fix some script bug in setup hyper

### CODE REVIEW

**Comment by Crazykev** [comment]
seems get stuck when execute CNI plugin

**Comment by Crazykev** [comment]
can't reproduce this even run `make test-e2e` in a brand new environment...

**Comment by feiskyer** [comment]
I'm trying to reproduce this problem.

**Comment by feiskyer** [comment]
Weird, didn't reproduce the problem.

**Comment by Crazykev** [comment]
@feiskyer This is network environment I get from one of the test, seems we disturb network and log stream from travis. Not sure whether we need change to a more special subnet.
```
+sudo ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:97:24:6b:52  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 42:01:0a:0a:14:b1  
          inet addr:10.10.20.177  Bcast:10.10.20.177  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1460  Metric:1
          RX packets:10053 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7465 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:125156728 (125.1 MB)  TX bytes:690180 (690.1 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:31 errors:0 dropped:0 overruns:0 frame:0
          TX packets:31 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:18373 (18.3 KB)  TX bytes:18373 (18.3 KB)

+sudo route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.10.20.1      0.0.0.0         UG    0      0        0 eth0
10.10.20.1      0.0.0.0         255.255.255.255 UH    0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
```

**Pull request merged**
