### PR TITLE
[NEED TEST]Check stderr in streaming test since upstream fixed

### PR DESCRIPTION
**Pull request by Crazykev**
Ref: #120 
Signed-off-by: Crazykev <crazykev@zju.edu.cn>

### CODE REVIEW

**Comment by feiskyer** [comment]
Let's check whether the CI is green now.

**Comment by Crazykev** [comment]
Two passed and one got stuck for unknown reason
```
run frakti e2e test case
Running Suite: Frakti e2e suite
===============================
Random Seed: 1492528420 - Will randomize all specs
Will run 21 of 21 specs
[k8s.io] Test PodSandbox 
  test stop PodSandbox
  /home/travis/gopath/src/k8s.io/frakti/test/e2e/pods.go:87
[BeforeEach] [k8s.io] Test PodSandbox
  /home/travis/gopath/src/k8s.io/frakti/test/e2e/framework/framework.go:61
[BeforeEach] [k8s.io] Test PodSandbox
  /home/travis/gopath/src/k8s.io/frakti/test/e2e/pods.go:35
[It] test stop PodSandbox
  /home/travis/gopath/src/k8s.io/frakti/test/e2e/pods.go:87
STEP: create a podSandbox with name
I0418 15:13:40.379549   22341 manager.go:161] RunPodSandbox from runtime service with request &RunPodSandboxRequest{Config:&PodSandboxConfig{Metadata:&PodSandboxMetadata{Name:create-simple-sandbox-for-stop9aa4b13a-2449-11e7-a910-42010a0a1464,Uid:e2e-cri-uid,Namespace:e2e-cri-namespace,Attempt:2,},Hostname:,LogDirectory:,DnsConfig:nil,PortMappings:[],Labels:map[string]string{},Annotations:map[string]string{},Linux:nil,},}
``` 
Let's try this again.

**Comment by Crazykev** [comment]
...travis stuck twich in go1.7 when try to run sandbox... Did this happen before?

**Comment by Crazykev** [comment]
@feiskyer Somehow, it works now, do we need test this again?

**Comment by feiskyer** [comment]
@Crazykev Let's try it again.

**Comment by feiskyer** [comment]
CI green again. Let's get this in.

**Pull request merged**
