### PR TITLE
Add tty resize support in attach/exec

### PR DESCRIPTION
**Pull request by Crazykev**
vendor k8s.io/kubernetes/pkg/kubelet/container to reuse `HandleResizing()`
since we need to vendor dockershim later, it should be fine to vendor so much code here.

Also lower lower k8s.io/client-go 1 commit to be compatible with apimachinery(according to update time in client-go and apimachinery repo)

@feiskyer PTAL

### CODE REVIEW

**Comment by resouer** [comment]
ref #50

**Comment by feiskyer** [comment]
@Crazykev Have you verified `kubectl attach` command? It didn't work in my settings:

```
# kubectl attach nginx-2371676037-bfj7x -i -t
Unable to use a TTY - container nginx did not allocate one
If you don't see a command prompt, try pressing enter.

ls
ls
ls
^Croot@ubuntu-0:~#
```

**Comment by Crazykev** [comment]
wired, it works for me.
```
$ cluster/kubectl.sh attach busybox-1102703165-qngr8 -i -t
Unable to use a TTY - container busybox did not allocate one
If you don't see a command prompt, try pressing enter.
ls
bin
dev
etc
home
lib
proc
root
sys
tmp
usr
var
```

**Comment by feiskyer** [comment]
@Crazykev Is tty also working?

**Pull request merged**
