### PR TITLE
Fix variable name typo

### PR DESCRIPTION
**Pull request by hangyan**

### CODE REVIEW

**Comment by hangyan** [comment]
@resouer There are already some errors about the api generated in the build, does it matter?

**Comment by resouer** [comment]
CI has already been fixed in #278 , just wait for that PR got merge.

**Comment by resouer** [comment]
Please rebase and CI should be fixed

**Comment by hangyan** [comment]
@resouer There are still some errors in the CI tests, Can you help me with it ?

**Comment by resouer** [comment]
Seems recent change break image pull: #286

Will take a look.

**Pull request merged**
