### PR TITLE
remove/stop not exist pod return success

### PR DESCRIPTION
**Pull request by Crazykev**
Signed-off-by: Crazykev <crazykev@zju.edu.cn>

### CODE REVIEW

**Comment by feiskyer** [comment]
CI failed:

test

**Comment by Crazykev** [comment]
It is not concerned with this patch, I'm also confused with it, ExecSync just randomly failed with empty result, I'll look deeper later.

**Comment by feiskyer** [comment]
Yep, the PR SGTM. Will restart the CI and check what will happen.

**Pull request merged**
