### PR TITLE
fixed grammatical issues and alternative images url

### PR DESCRIPTION
**Pull request by ZouRui89**
An alternative image website is available when google website can not be reached with successful network connection.

### CODE REVIEW

**Comment by ZouRui89** [comment]
I have completed the registration

**Comment by resouer** [comment]
@ZouRui89 Thank you very much for contributing!

While I think it would be better to add a section of `Trouble Shooting` to include your change.

**Comment by ZouRui89** [comment]
I have completed the registration.

**Comment by resouer** [comment]
cc @bergworf

**Comment by resouer** [comment]
@ZouRui89 Please squash your commit into single one, then we can merge this.

**Pull request closed without merging**
