### PR TITLE
Split Unit Test and E2E test in seperate Travis CI Stages

### PR DESCRIPTION
**Pull request by asifdxtreme**
Splitted Unit test and E2E test in seperate stages of Travis CI so that it's easy for user to debug what went wrong in the CI

### CODE REVIEW

**Comment by asifdxtreme** [comment]
@dchen1107 @feiskyer @resouer Can you please help me to re-trigger the CI, https://travis-ci.org/kubernetes/frakti/builds/261757867?utm_source=github_status&utm_medium=notification I guess this is CI env issue and not the real issue from the code

**Comment by resouer** [comment]
Just re-triggered

**Comment by feiskyer** [comment]
@asifdxtreme Thanks for adding the cool CI stages. The CI failed because of a known problem, which should be fixed in #192 (but it still have a little problem).

**Comment by asifdxtreme** [comment]
@feiskyer lets wait for 192 to get merged then we can rebase this PR

**Comment by feiskyer** [comment]
re-trigger travis CI again.

**Comment by asifdxtreme** [comment]
@feiskyer  thanks the CI passed now, please help me to merge this PR

**Comment by feiskyer** [comment]
@asifdxtreme Thanks. Merged.

**Pull request merged**
