### PR TITLE
Support dns options and searches

### LINKED ISSUE #115: Support dns domain and options
Currently, only nameserver is set in `/etc/resolv.conf`. We should also set dns search domain and options.

Expected `/etc/resolv.conf` example:

```
search default.svc.cluster.local svc.cluster.local cluster.local home
nameserver 10.96.0.10
options ndots:5
```

### PR DESCRIPTION
**Pull request by feiskyer**
Closes #115.

cc @resouer

### CODE REVIEW

**Comment by feiskyer** [comment]
CI failed because of an upstream hyperd issue:

pasted image at 2017_04_07 09_26 pm

**Comment by resouer** [comment]
Change LGTM, should we merge this?

**Comment by feiskyer** [comment]
@resouer Wait me add a workaround of https://github.com/hyperhq/hyperd/issues/604

**Comment by feiskyer** [comment]
@resouer Ready for review&merge.

**Pull request merged**
