### PR TITLE
Add e2e test framework in frakti

### PR DESCRIPTION
**Pull request by Crazykev**
1. add e2e test framework
2. add some scripts to build and run e2e tests
3. add a simple create podsandbox e2e test case as an example
4. fix some bugs in create podsandbox
5. add docs, describing how to run e2e tests

Ready for review. @feiskyer @resouer

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/23)

### CODE REVIEW

**Comment by feiskyer** [comment]
Boilerplate missing or errored in: ././hack/lib/logging.sh.

**Comment by Crazykev** [comment]
Boilerplate updated.  While `hack/test-go.sh` will run all test files, e2e test package `k8s.io/frakti/test/e2e` should not be run in this way, should we filter this package? @feiskyer

**Comment by feiskyer** [comment]
@Crazykev Yes, e2e test shouldn't be included in `hack/test-go.sh`, it should be separated.

I think this e2e test can also be running in traivs, could you also add hyperd installation scripts and start hyperd on e2e tests?

**Comment by resouer** [comment]
@Crazykev  please update you pr :)

**Comment by Crazykev** [comment]
PR updated. FYI, hyperd install script still doesn't work well, needs do some work on hyperd deb package or just build hyper binaries inside travis before this PR could work. @resouer @feiskyer

**Comment by Crazykev** [comment]
@feiskyer Updated.

**Comment by feiskyer** [comment]
lgtm. thanks.

**Pull request merged**
